
<div class="left-side panels">
  <div class="wrapper-tb-l">
  <form method="POST" action="?page=bug-action" enctype="multipart/form-data">

    <div class="field-form" >
      <input type="text" name="title" class="input-text" placeholder="Bug Title" required>
    </div> 

    <div class="field-form"> 
      <textarea rows="7" cols="35" name="bug_description" class="input-text" placeholder="Description" required></textarea>
    </div> 

    <div class="field-form">
      <label>*Attach file:
        <input type="file" id="id-img" accept="image/jpeg,image/png" name="uploadfile" required></br>
      </label>
    </div> 

    <div class="field-form">
      <input type="submit" class="input-submit" value="Submit">
    </div>  

  </form>
  </div>
</div>
