	<div class="user-info-wrapper license-item">
		<div class="license <?php print $pay_class; ?>">
			<div class="license-title"><span>License: AC2001</span><?php print $lid; ?></div>
			<div class="license-title"><span>License Type: DEMO</span></div>
			<div class="license-authcode"><span>Authcode: </span><?php print ' '.$authcode; ?></div>
			<div class="license-regcode"><span>Regcode: </span><?php print ' '.$regcode; ?></div>
			<a href="?page=<?php print $link_parameters[1]; ?>"><?php print $link_parameters[0]; ?></a>
		</div>
	</div>
