<div class="main-wrapper">
	<div class="left-side">
		<form method="post" class="form-payment" action= "https://www.paypal.com/cgi-bin/webscr">
		<img id="paypal-logo" src="/files/img/PayPal-logo.png" alt="">	
		<div class="license-info">
			<div>License Type: Long Term</div>
			<div>Price: 89.67$ </div>
		</div>
		<input type="hidden" name="cmd" value="_xclick">
		<input type="hidden" name="business" value="support@automatica.co.ua">
		<input type="hidden" name="item_name" value="Automatic OPC HDA Client (License)">
		<input type="hidden" name="item_number" value="1">
		<input type="hidden" name="amount" value="89.67">
		<input type="hidden" name="no_shipping" value="1">
		<input type="hidden" name="notify_url" value="automatica.co.ua/?page=notify-payment">
		<input type="submit" class="buy-route" value="Buy License 89.67$">
		</form>
	</div>
</div>