<div class="left-side">
  <h1>Enter your authentication code</h1>
  <form method="POST" class="form-comment" action="?page=authcode-action&lid=<?php print $lid; ?>">

    <div class="field-form"> 
      <input type="text" name="authcode" class="input-text"  placeholder="Enter your authentication code" required>
    </div> 

    <div class="field-form">
      <input type="submit" class="input-submit" value="Submit">
    </div>
  </form>
</div>
<div class="right-side">
	<h1>Info</h1>
	<p><span class="abz">If you hit this page means you paid</span> a license for the software. You need to enter your authentication code, and wait until it is on the supervisor will generate a registration code that you enter in the application.</p>
  <p>
    <h2>Please, take to menu "About->License"</h2>
  </p>
  <img src="/files/img/rerg.png" alt="">
</div>