<div class="wrapper-tb-l">
  <form method="POST" action="?page=add-file-post" enctype="multipart/form-data">

    <div class="field-form" >
      <input type="text" name="filetitle" class="input-text" placeholder="File title" required>
    </div> 

    <div class="field-form">
      <label>*Attach file:
        <input type="file" id="id-img" accept="image/jpeg,image/png" name="uploadfile" required></br>
      </label>
    </div> 

    <div class="field-form">
      <input type="submit" class="input-submit" value="Submit">
    </div>  

  </form>
</div>