<div class="main-wrapper">
<h1>OPC HDA (OPC Historical Data Access) standardizes communication for retrieving archived process data.</h1> 

<p>OPC HDA is the solution for accessing historical data across multiple vendors. OPC HDA will do for real-time databases what Microsoft's ODBC (Open Database Connectivity) did for relational databases. Recall that even as recently as 1995, ODBC was only available for a select group of relational database products. But today, it is rare to find a large-scale Microsoft Windows-based deployment of a non-ODBC compliant database. Similarly, with OPC HDA, today's standards-savvy engineers will be much better prepared to escape the limitations of proprietary process historian solutions. </p>

<h2>Benefits include:</h2>
	<li class="opc-lists">Eliminate custom driver development costs</li>
	<li class="opc-lists">Adapt rapidly to changing information management needs</li>
	<li class="opc-lists">Connect to any Process Historian</li>
	<li class="opc-lists">Seamlessly change data sources using off-the-shelf software </li>

<img src="files/img/tutorial-screenshot.jpg" alt="" id="img-tutorial"></br>

<h2>Providing interoperability</h2>

<p>In the past, each Process Historian had its own proprietary communication method. Applications that made use of historical process data were always tightly coupled to their respective Process Historian, or at the very least, they required a proprietary driver to make the connection. When someone needed data from a different Process Historian, a new driver would have to be written. This limited the effectiveness and reach of the applications because the necessary drivers were usually unavailable. <p></br>

<h2>The problem affected everyone:</h2>

<li class="opc-lists">Process Historian vendors could not make their data available to all applications</li>
<li class="opc-lists">Application vendors could not access data from all process historians</li>
<li class="opc-lists">Because of the above, users could not select a best-of-breed solution</li>

<h2>OPC HDA standardizes the communication between the Process Historian and its associated applications. Consequently:</h2>

<li class="opc-lists">HDA enables any application to connect to any data source.</li>
<li class="opc-lists">Any application that makes use of historical data can seamlessly change its data source without any reprogramming</li>
<li class="opc-lists">Users have the flexibility they need to rapidly adapt to changing information management needs.</li>

Thus, like OPC DA, OPC HDA enables smooth interoperability between the applications that archive data and the applications that require it.

<h2>Relationship of OPC HDA with other standard specifications</h2>

<p>OPC HDA is similar to other well-known and accepted communication standards. The following is a brief comparison to the most popular standards. </p></br>

<p><strong>Relationship with OPC DA:</strong> past and present OPC HDA and OPC DA are very close cousins and widely complementary protocols. Both have the same data types, and both transfer process values. In fact, the biggest difference between the two is that DA transfers real-time values, whereas HDA transfers archived values. For instance, a typical Process Historian would have an OPC DA client to access real-time values from a control system. The Process Historian would then make this data available to everyone using an OPC HDA server. In other words, all values archived using the DA client can be accessed using HDA. So DA is used to find the current value of a point (or tag), while HDA is used to find the historical values of that point.</p></br>

<p><strong>Relationship with OPC XML:</strong> viewing over the Internet Although OPC XML and HDA are intended for different uses, they are in fact complementary. XML brings process control data to the Intranet and Internet in general, and to the web specifically. Once users move their applications from the Intranet to the Internet they quickly find that their applications can no longer be used for real-time control and display of data that changes rapidly. After all, Internet access times and bandwidth can rarely be guaranteed. Rapid access and retrieval of historical data is more important than ever, and an OPC XML server can get its data source directly and quickly from an HDA server so that historical data can be accessed from anywhere on the Internet. </p></br>

<p><strong>Relationship with ODBC:</strong> relational versus process data ODBC (Open Database Connectivity) is a highly accepted standard for Microsoft Windows-based RDBMS (Relational Database Management Systems). Therefore, both ODBC and OPC HDA are used for retrieval of historical data. The difference is that ODBC is optimized for relational data, whereas OPC HDA is optimized for process data. (Although a discussion on the differences between an RDBMS and a Process Historian is an interesting one, it is the subject for another day.) While ODBC can be used in place of OPC HDA, the implementation time will be much greater, and the resulting performance will be poor in comparison with a pure OPC HDA implementation.</p></br>

<div class="original-source-wrapper">
	<a href="http://www.matrikonopc.com/resources/opc-specifications/opc-hda.aspx?print=Y" class="slyle-link-1">Original Source</a>
</div>

</div>
