<div class="main-wrapper">
	<div class="product-page">
		<h1>Automatic OPC HDA Client</h1>
		<h2>OPC HDA Client to ODBC</h2>
		<p><span class="abz">Automatic OPC HDA Client</span> is designed to collect technical information to the energy metering, SCADA systems and other complex systems which have on board OPC HDA interface. The application works with the database MS SQL Server. Also spine support ODBC data source. ODBC or MS SQL Server. 
		<div class="left-side">
			<img class="systems-img" src="/files/img/opc hda client odbc.png" alt="">
		</div>
		<div class="right-side">
			<img class="systems-img" src="/files/img/opc hda client ms sql server.png" alt="">
		</div>
		</p>
		<p><span class="abz">Automatic OPC HDA Client includes</span> a module for accounting about reading information from the systems. This report on the reading you can watch in the application or Web interface. This report makes it possible to analyze in detail how was the session data reading. You can also view the data in the database that have been read from the OPC tag. This option is very useful in the formation of the final report for the service Energetics.
		<div class="left-side">
			<img class="systems-img" src="/files/img/opc hda client report about read.png" alt="">
		</div>
		<div class="right-side">
			<img class="systems-img" src="/files/img/opc hda client tag-tabelname.png" alt="">
		</div>	
		</p>
		<p>
			<span class="abz">Due to the fact that all data</span> to gather technical data in the same database for all tags structure, such data can easily be used in their existing accounting systems. When you add a tag to a common reading list is given in the table that the data will be read. All table names are generated automatically based on the name tag. Also, the name of the table, you can set yourself ..
		</p>
	</div>
</div>


